name: Car Rent CI

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v3.5.3

      - name: Deploy para a VPS
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.sshPrivateKey }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.remoteHost }}
          REMOTE_USER: ${{ secrets.remoteUser }}
          REMOTE_PORT: ${{ secrets.remotePort }}
          TARGET: ${{ secrets.remoteTarget }}
      
      - name: Run Docker containers
        run: docker-compose -f "docker-compose.yml" up -d --build